from static.answers.awoo 		import answers as awoo
from static.answers.baka 		import answers as baka
from static.answers.bite 		import answers as bite
from static.answers.bulk 		import answers as bulk
from static.answers.bye 		import answers as bye
from static.answers.coffee 		import answers as coffee
from static.answers.cold 		import answers as cold
from static.answers.cookies		import answers as cookies
from static.answers.facepalm	import answers as facepalm
from static.answers.hello		import answers as hello
from static.answers.idk			import answers as idk
from static.answers.itsok 		import answers as itsok
from static.answers.kiss 		import answers as kiss
from static.answers.lapk 		import answers as lapk
from static.answers.lick 		import answers as lick
from static.answers.meh 		import answers as meh
from static.answers.morning 	import answers as morning
from static.answers.mur 		import answers as mur
from static.answers.night		import answers as night
from static.answers.not_nyan	import answers as not_nyan
from static.answers.notfood 	import answers as notfood
from static.answers.nyahaha 	import answers as nyahaha
from static.answers.nyan 		import answers as nyan
from static.answers.rawr 		import answers as rawr
from static.answers.respect 	import answers as respect
from static.answers.rkn 		import answers as rkn
from static.answers.rufus 		import answers as rufus
from static.answers.sad 		import answers as sad
from static.answers.tea 		import answers as tea
from static.answers.tygydyk		import answers as tygydyk
from static.answers.vas3k 		import answers as vas3k
from static.answers.vivivi 		import answers as vivivi
from static.answers.warm 		import answers as warm