from words.classes import Sticker, Text, Other
name = 'Ханекава'

lewd ={
'nyan' : (		Text	('Ня ^_^', 'nyan'), 
				Text	('Няяяя~', 'nyan'), 
				Text	('Няу *-*', 'nyan'), 
				Text	('Nya', 'nyan'), 
				Text	('Мяяяяяу', 'nyan'),),
'mur' : (		Text	('Муррр'), 
				Text	('Мур'), 
				Text	('Пурр'),),
'awoo' : (		Text	("Awoo =^o^= ~"), 
				Text	('Awoo'), 
				Text	('Авууу!'),),
'bite' : (		Text	('Кусь, няха ^_^', 'nyan'), 
				Text	('*Нежно кусь за ушко*', 'lewd'), 
				Text	('%s аккуратно кусает шею*', 'lewd'),),
'lick' : (		Text	("Лизь тебя в щечку", 'lewd'), 
				Text	('*покраснела*', 'lewd'), 
				Text	("Нежно лизь ушко", 'lewd'),),
'kiss' : (		Text	('%s нежно целует в щечку', 'lewd'), 
				Text	('%s эротично целует по-французски', 'lewd'),),
'lapk' : (		Text	('%s расстегивает пуговку расширяя декольте*', 'lewd'),),
'rawr' : (		Text	('Ну чего ты, лапочка'),),
'meh' : (		Text	('*Прижимается и гладит*'),
				Text	('Не печалься, *целует в лоб и обнимает*'),),
'baka'		: (	Sticker	("CAADAgADwgADlS2QCoVvM6hLrHuxFgQ"),),
'morning' : (	Text	('Утречка, не устал после вчерашнего?', 'lewd'), 
				Text	('Привет))'), 
				Text	('Охайо^^'),
				Sticker	('CAADAgAD2AADOYhhEqPQlBGL82DmFgQ'),
				Sticker	('CAADAgADAwEAAjmIYRJkhs5iEOzAahYE'),),
'night' : (		Text	('Эротических сновидений, *цем*', 'lewd'), 
				Text	('Сладких снов, дорогуша'), 
				Text	('Оясуминасай, Аната *-*'),),
'hello' : (		Text	('%s приветственно целует*', 'lewd'),
				Sticker	('CAADAgADCAAD5ODJIxqwyU-ZhSOBFgQ'),),
'warm' : (		Text	('%s садится голышом на подоконник*', 'lewd'), 
				Text	(f'*У {name.replace("а", "ы")} вода пролилась на маечку и просвечивает*', 'lewd'), 
				Text	('%s раздевается, чтобы охладится*', 'lewd'),),
'cold' : (		Text	('%s шалит под котацу чтобы согрется*', 'lewd'), 
				Text	('%s дрожит от холода прикасающихся рук*', 'lewd'), 
				Text	('%s греется, обнимая голышом*', 'lewd'),),
'sad' : (		Text	('*Прижимается и гладит*'),
				Text	('Не печалься, *целует в лоб и обнимает*'),),
'tygydyk' : (	Text	('Сейчас сделаем тыгыдык в твоих штанах^^'),),
'comp_p': (		Text	('<a href="https://vas3k.ru/blog/computational_photography/">Вычислительная Фотография</a>')
)}