from words.classes import Sticker, Text, Other
name = 'Ханекава'

nyan = {
'nyan' 		: (	Text	('Ня ^_^', 'nyan'), 
				Text	('Няяяя~', 'nyan'), 
				Text	('Няу *-*', 'nyan'), 
				Text	('Nya', 'nyan'), 
				Text	('Мяу', 'nyan'),
				Sticker	('CAADAgADaCkAAuCjggc25OCNdwABB-QWBA', 'nyan'),
				Sticker	('CAADAQADUAcAApEpAAEQJrWBxenFdf0WBA', 'nyan'),
				Sticker	('CAADAQADnyMAAnj8xgU0Q-u3iNi_BhYE', 'nyan'),
				Sticker	('CAADAgAD8QgAAotGbSd1yMpKZ2deghYE', 'nyan'),
				Other	(2),),
'mur' 		: (	Text	('Мур', 'nyan'), 
				Text	('Пурр', 'nyan'), 
				Text	('Murrr', 'nyan'), 
				Text	('Purrr', 'nyan'),
				Sticker	('CAADAQADUAcAApEpAAEQJrWBxenFdf0WBA', 'nyan'),),
'awoo' 		: (	Text	("Awoo =^o^= ~", 'nyan'), 
				Text	('Awoo', 'nyan'), 
				Text	('Авууу!', 'nyan'),),
'bite' 		: (	Text	('Кусь, няха ^_^', 'nyan'), 
				Text	('Кусь',), 
				Text	('Кусь, б-бака >_<', 'scar'),
				Sticker	('CAADAgADxQADrHkzBnUN64jQMLBoFgQ', 'angr'),),
'lick' 		: (	Text	("Лизь тебя <3", 'lewd'), 
				Text	("Лизь~", 'lewd'), 
				Text	('*покраснела*', 'lewd'),),
'lapk'		: (	Sticker	('CAADAgAD_GcAAuCjggcc4yEXnt2GTBYE', 'lewd'),),
'rawr'		: (	Text	('Ррр!', 'angr'),
				Text	('Равр!', 'angr'), 
				Text	('Rawr!', 'angr'), 
				Text	('Rrr!', 'angr'),
				Sticker	('CAADAgAD1j0AAuCjggeCzkUtb_PLChYE'),),
'meh'		: (	Text	('Вздыхает'), 
				Text	('Пушисто!'),),
'bulk'		: (	Text	('Буууульк!', 'nyan'), 
				Text	('Бууууль', 'nyan'), 
				Text	('Буль-буль', 'nyan'),),
'baka'		: (	Sticker	("CAADAgADCQADlS2QCt_F3mU_Ekl5FgQ"),),
'idk'		: (	Text	("Хрен знает!"),
				Sticker	("CAADAgADxgADFTCdEMtnrnydTqyFFgQ"),
				Sticker	("CAADAgADxgADFTCdEMtnrnydTqyFFgQ"),
				Sticker	("CAADAgADXgADfEkIHLp8ZxiHco1PFgQ"),
				Sticker	("CAADAQADgyMAAnj8xgVdT-nJb8X-4RYE"),
				Sticker	("CAADAQADNxUAAnj8xgUDRa4NoDjQuxYE"),
				Sticker	("CAADAgAD5QQAAm8Odx33vxPNKJ2mbRYE"),
				Sticker	("CAADAgAD2gQAAm8Odx07gps43J10HBYE"),
				Sticker	("CAADAgADrjcAAuCjggcOsTcSgkzZghYE"),),
'respect'	: (	Sticker	("CAADAgAD2h0AAuCjggdT4wFdB92SAxYE"),
				Sticker	("CAADAgADSAADn-OXGFg_k6j563-iFgQ"),
				Other	(6),
				Other	(7),
				Other	(8),
				Other	(9),
				Other	(10),),
'facepalm'	: (	Sticker	("CAADAgADvB0AAuCjggf66g_-Uf4bDxYE"),
				Sticker	("CAADAgADNwADn-OXGGVJ7J_rnzbCFgQ"),
				Sticker	("CAADAgADbQADfEkIHGV7XqeT-sfkFgQ"),),
'rkn'		: (	Sticker	('CAADAgADkggAArcKFwABz2XObTTm3_YWBA'),
				Sticker	('CAADAgADYAgAArcKFwABjwo8AfSwZxkWBA'),
				Sticker	('CAADAgAD-gcAArcKFwAB5A4q2-1uG9kWBA'),
				Sticker	('CAADAgAD9AcAArcKFwABrL8eiOpXVxUWBA'),
				Sticker	('CAADAgAD2wcAArcKFwABEA9br52tHcgWBA'),
				Sticker	('CAADAgADOQADlS2QCiliyCPelGPSFgQ'),),
'notfood'	: (	Sticker	('CAADAgADQgADlS2QCmmQ04GpsSVBFgQ'),),
'morning'	: (	Text	('Утречка, няшка^^'), 
				Text	('Утра'),
				Text	('Привет)'), 
				Text	('Охайо^^'),
				Sticker	('CAADAgAD0mMAAuCjggfe1LWingZagRYE'),
				Sticker	('CAADAgADkCUAAuCjggeCPV98a6NIvhYE'),
				Sticker	('CAADAgADQikAAuCjggcJ3jT9RTZm-hYE'),
				Sticker	('CAADAgADXgEAAu243wpLqt8sTQivpRYE'),
				Sticker	('CAADAgAD2AADOYhhEqPQlBGL82DmFgQ'),
				Sticker	('CAADAgAD0mMAAuCjggfe1LWingZagRYE'),
				Sticker	('CAADAgADkCUAAuCjggeCPV98a6NIvhYE'),
				Sticker	('CAADAgADQikAAuCjggcJ3jT9RTZm-hYE'),
				Sticker	('CAADAgADwR0AAuCjggfyS_hgl5kxYRYE'),),
'night'		: (	Text	('Доброй ночи'), 
				Text	('Приятных снов'), 
				Text	('Оясуминасай'),
				Sticker	('CAADAgADuGcAAuCjggcEK4Wuw6OReBYE'),
				Sticker	('CAADAgAD5h0AAuCjggekwJfpF4blcxYE'),
				Sticker	('CAADAgAD5x0AAuCjggfUw9fjxFR09BYE'),
				Sticker	('CAADBQADRwIAAunPYgjfF0mi4c26kRYE'),
				Sticker	('CAADAgADsyUAAuCjggerF63AIh5OCRYE'),
				Sticker	('CAADAgADt2cAAuCjggeEL-XEwL_VoRYE'),
				Sticker	('CAADAgAD32cAAuCjggeCGprfvE5HNBYE'),
				Sticker	('CAADAgAD4GcAAuCjggfs73jN2zfFeBYE'),
				Sticker	('CAADAgAD1mcAAuCjggcOLod87WZY0RYE'),
				Sticker	('CAADAgADpDcAAuCjggeHV6fwXeE7zxYE'),),
'hello'		: (	Text	('Приветствую'), 
				Text	('Здравствуй'),
				Sticker	('CAADAgAD0mMAAuCjggfe1LWingZagRYE'),
				Sticker	('CAADAgADkCUAAuCjggeCPV98a6NIvhYE'),
				Sticker	('CAADAgADQikAAuCjggcJ3jT9RTZm-hYE'),
				Sticker	('CAADAgADwR0AAuCjggfyS_hgl5kxYRYE'),),
'bye'		: (	Sticker	('CAADAgAD5x0AAuCjggfUw9fjxFR09BYE'),
				Sticker	('CAADBQADRwIAAunPYgjfF0mi4c26kRYE'),
				Sticker	('CAADAgADsyUAAuCjggerF63AIh5OCRYE'),
				Sticker	('CAADAgADpDcAAuCjggeHV6fwXeE7zxYE'),),
'warm'		: (	Text	('{} открывает окно*'), 
				Text	('{} кушает мороженое*'), 
				Text	('{} включает кондиционер*'),),
'cold'		: (	Text	('{} укутывается в пледик*'), 
				Text	('Бррр!'), 
				Text	('{} дрожит от холода*'), 
				Text	('{} включает обогреватель*'),),
'sad'		: (	Text	('Не печалься, няха^^'),),
'tygydyk'	: (	Text	('Тыгыдык!'),),
'vivivi'	: (	Text	('Вививи'), 
				Text	('{} заводит старый жигуль*'),),
'timur'		: (	Text	('Копай, бля!', 'scar'),
				Text	('{} прячется за занавеской* >_<', 'scar'),
				Sticker	('CAADAgADWCkAAuCjggdo5gnw-q-JfRYE', 'scar'),
				Sticker	('CAADAgADrDcAAuCjggft5Gh808VgXRYE', 'scar'),),
'rufus'		: (	Text	('<a href="https://rufus.ie/">Rufus</a>'),),
'comp_p'	: (	Text	('<a href="https://vas3k.ru/blog/computational_Othergraphy/">Вычислительная Фотография</a>')
)}