from words.classes import Sticker, Text, Other
name = 'Ханекава'
scar = {
'nyan' : (		Text	('Н-н-н-я...'), 
				Text	('%(name)s някнула из-за дивана*'),),
'mur' : (		Text	('Мр'), 
				Text	('%(name)s испуганно тихо мурлыкает*'),),
'awoo' : (		Text	("Aв-ву... >_<"), 
				Text	('Aw-wo'),
				Sticker	('CAADAQADPQcAApEpAAEQfBRxUdnXev0WBA'),),
'bite' : (		Text	('Помогите!'), 
				Text	('Ааа, кусают!'),
				Sticker	('CAADAgADxQADrHkzBnUN64jQMLBoFgQ', 'angr'),),
'lick' : (		Text	('Отстань, извращенец!'), 
				Text	('%(name)s сжалась от страха, не в силах пошевелится*'),),
'kiss' : (		Text	('*Убегает*'),),
'lapk' : (		Text	("Ааа, не надо!*%(name)s убегает в страхе*"),),
'rawr' : (		Text	('%(name)s тихо рычит за углом*'),),
'meh' : (		Text	('Вздыхает'),),
'morning' : (	Text	('Ут-тра...>_<'),),
'night' : (		Text	('%(name)s пытается тихонько выйти из комнаты*'),),
'hello' : (		Text	('Здравствуй'),),
'warm' : (		Text	('%(name)s открывает окно*'), 
				Text	('%(name)s включает кондиционер*'),),
'cold' : (		Text	('%(name)s укутывается в пледик*'), 
				Text	('Бррр!'), 
				Text	('%(name)s дрожжит от холода*'), 
				Text	('%(name)s включает обогреватель*'),),
'timur' : (		Text	('%(name)s прячется за занавеской* >_<'),),
'comp_p': (		Text	('<a href="https://vas3k.ru/blog/computational_photography/">Вычислительная Фотография</a>')
)}