en_service = {
	#admin_bot.py (настройки бота)
	'chat_on'			: 'Replier turned on.',
	'chat_off'			: 'Replier turned off.',
	'lang_change'	 	: 'Language changed to %s.',
	'lang_error'	 	: 'Error while changing language.',
	'mood_change'	 	: 'Mood changed to %s.',
	'mood_error'	 	: 'Error while changing mood.',
	'admin_user_state'	: 'Replier mode of user **{0}** {1}.',
	'on'				: 'turned on',
	'off'				: 'turned off',
	'ban'				: 'banned',
	'options'			: 'What option do you want to change?',
	"chat_stats"		: 'Chat settings',
	'vw_user'			: 'View user conf',
	'ch_user'			: 'Change user conf',
	'ch_user?'			: 'What mode do you want to turn?',
	'state'	 			: 'State',
	'mood'	 			: 'Mood',
	'lang'	 			: 'Language',
	'nyan'				: 'cute', 
	'lewd'				: 'lewd', 
	'angr'				: 'angry', 
	'scar'				: 'scared',
	'uon'				: 'On',
	'con'				: 'On', 
	'uoff'				: 'Off',
	'coff'				: 'Off', 
	'uban'				: 'Ban',
	'ru'				: '🇷🇺', 
	'en'				: '🇬🇧',
	'unban_error'		: 'Error, replier not blocked.',
	'permission_error'	: 'Sorry, you should be admin for this.',
	'same_user_cond'	: 'User in this mode.',
	#ролеплей
	'hug'				: 'huged',
	'kiss'				: 'kissed',
	'koos'				: 'gently bited',
	'lick'				: 'licked',
	'jamk'				: 'intensly hugged',
}