triggers	=	(
	('awoo',			'nyan',	r'\b([аa][вw][уo]+)\b'),
	('baka',			'nyan',	r'\b([бb][аяa]+[кk][аa]+)\b'),
	('bite',			'nyan',	r'\b(ку+ськ?)\b'),
	('bulk',			'nyan',	r'\b(бу+льк?)\b'),
	('lapk',			'nyan',	r'\b([лц]а+пк?)\b'),
	('meh',				'nyan',	r'\b((м+ех)|(me+h))\b'),
	('not_nyan',	'nyan',	r'\b(((не|not)	){1}[нмnm][ьy]?[яa]+[нn]?[вфf]?[уu]*(c?k|к)?)\b'),
	('nyan',			'nyan',	r'\b((?<!не	)(?<!not	)[нмnm][ьy]?[яa]+([нn]?|[вфf]?|[уu]*|(c?k|к)?))\b'),
	('kiss',			'nyan',	r'\b((ц[её]+мк?)|(kiss))\b'),
	('lick',			'nyan',	r'\b((ли+зьк?)|(li+ck))\b'),
	('mur',				'nyan',	r'\b(([mp]u*r+k*)|([мп]у*р+к*))\b'),
	('rawr',			'nyan',	r'\b(([рr]+[аяa]+[вw][рr]+)|(г?(r|р)[rр]+))\b'),
	('tygydyk',		'nyan',	r'\b(тыгыдык)\b'),
	('vivivi',		'nyan',	r'\b((ви){2,5}|(vi){2,5})\b'),
 
	('facepalm',	'memes',	r'\b((facepalm)|(ф[еэ]йспалм))\b'),
	('idk',				'memes',	r'\b(хз)\b'),
	('itsok',			'memes',	r'\b(и	та+к	сойд[её]+т)\b'),
	('notfood',		'memes',	r'\b(нееш)\b'),
	('nyahaha',		'memes',	r'\b((скороговорк[ау])|([нмnm][ьy]?[яa]+([hх][aа]){2,5}))\b'),
	('respect',		'memes',	r'\bf\b'),
	('rkn',				'memes',	r'\b((ркн)|(rkn)|(роскомнадзор))\b'),
 
	('cold',			'empathic',	r'\b((про)?хо*л[оа]дно(вато)?)\b'),
	('sad',				'empathic',	r'\b((печаль(н(ова(т|(с*теньк)))*о))|(груст(ь|(н(ова(т|(с*теньк)))*о))))\b'),
	('warm',			'empathic',	r'\b(жа+рко(вато)?)\b'),
 
	('coffee',		'food',	r'\b((налей|(по)?дай)	кофе)\b'),
	('cookies',		'food',	r'\b(((по)?дай)	печен(ьку|ек))\b'),
	('tea',				'food',	r'\b((налей|(по)?дай)	ча(я|ю))\b'),
	
	('morning',		'greeters',	r'\b(((добро(го)?	)?у+тр(е(чк)|ец)*а+)|(оха(ё|йо)+)|((доб)*ран((оч)*к[уа])))\b'),
	('hello',			'greeters',	r'\b((приве+т(ству((ю)|(ем))*)*)|(здра+вствуй(те)*)|(ха+(й|юшки))|(h(i+|e(ll|ww)o+)))\b'	),
	('bye',				'greeters',	r'\b(до	встре+чи+)|(проща+(ва)?й(те)?)|((good	)*bye)|(see	you)\b'),
	('night',			'greeters',	r'\b((но+чи)|(сно+в)|(оясуми(насай)?)|(good	night)|(sweet	dreams))\b'),
)
