from words.triggers.awoo			import answers as awoo
from words.triggers.baka			import answers as baka
from words.triggers.bite			import answers as bite
from words.triggers.bulk			import answers as bulk
from words.triggers.bye				import answers as bye
from words.triggers.cold			import answers as cold
from words.triggers.facepalm	import answers as facepalm
from words.triggers.nyahaha		import answers as nyahaha
from words.triggers.hello			import answers as hello
from words.triggers.idk				import answers as idk
from words.triggers.itsok			import answers as itsok
from words.triggers.kiss			import answers as kiss
from words.triggers.lapk			import answers as lapk
from words.triggers.lick			import answers as lick
from words.triggers.meh				import answers as meh
from words.triggers.morning		import answers as morning
from words.triggers.mur				import answers as mur
from words.triggers.night			import answers as night
from words.triggers.notfood		import answers as notfood
from words.triggers.nyahaha		import answers as nyahaha
from words.triggers.nyan			import answers as nyan
from words.triggers.rawr			import answers as rawr
from words.triggers.respect		import answers as respect
from words.triggers.rkn				import answers as rkn
from words.triggers.rufus			import answers as rufus
from words.triggers.sad				import answers as sad
from words.triggers.timur			import answers as timur
from words.triggers.tygydyk		import answers as tygydyk
from words.triggers.vas3k			import answers as vas3k
from words.triggers.vivivi		import answers as vivivi
from words.triggers.warm			import answers as warm